[package]
name = "snake"
version = "0.1.0"
authors = ["onasauri <onasauri@gmail.com>"]

[dependencies]
ndarray = { version = "0.8", features = ["serde"] }
preferences = "1.1"
rand = "0.3"
sdl2 = "0.29"
serde = "0.9"
serde_derive = "0.9"
